### ISSUE TITLE
Changelog / tags

### ISSUE THREAD

**Issue by johnjohndoe** [REPLicated/classpath-collision-detector#12]
Thanks for creating this plugin. I would very much appreciate if you can maintain a changelog in some kind of way. It could be a `CHANGELOG.md` in the root of the project or release notes in GitHub's release feature. Also Git tags are a good idea.

**Comment by REPLicated** [comment]
Good point. Added a `CHANGELOG.md` and will create an (annotated) Git tag when releasing.
