### ISSUE TITLE
`detectCollisions` tasks never up-to-date

### ISSUE THREAD

**Issue by boris-petrov** [REPLicated/classpath-collision-detector#15]
According to Gradle, that's because:

```
Caching disabled for task ':project:detectCollisions' because:
  No outputs declared
Task ':project:detectCollisions' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
```

**Comment by REPLicated** [comment]
Yes, that's indeed what is happening, thanks.

Im going to fix this by producing a minimal report as output.

**Comment by boris-petrov** [comment]
@REPLicated I believe this task should not have `outputs` so this is going to work fine: `outputs.upToDateWhen { true }` (or the equivalent using the Java API). But you have to specify `inputs` - that would be the configuration that is configured I guess. I think that would fix this issue and make it work correctly?

Also, *thank you* for the **awesome** plugin!

**Comment by REPLicated** [comment]
@boris-petrov : The inputs should already be properly declared.

You are right that `outputs.upToDateWhen { true } ` should work, but in the end I decided  to create a simple ` build/reports/classpath-collisions.txt` anyway, in addition to the output logged via the Gradle API to stdout/stderr. This simplifies collecting results as CI artifacts for later inspection if needed.

Release of the change is still pending but I should find some time next week.

**Comment by REPLicated** [comment]
https://github.com/REPLicated/classpath-collision-detector/commit/4e19c3760ea8d3e49f602255dccea286ecbe1a55
